#! Name
name: sip3-salto

#! Vert.x
#vertx:
#  instances: 1

#! Server
server:
  uri: udp://0.0.0.0:15060
  buffer-size: 65535
#  ssl:
#    key-store: ...
#    key-store-password: ...

#! Metrics
#metrics:
#  logging:
#    step: 1000
#  influxdb:
#    uri: http://127.0.0.1:8086
#    db: sip3
#    step: 1000
#    retention-duration: 7d
#  stasd:
#    host: 127.0.0.1
#    port: 8125
#    step: 1000
#    flavour: datadog