#! Name
name: sip3-salto

#! Vert.x
#vertx:
#  instances: 1

#! Mongo
#mongo:
#  uri: mongodb://127.0.0.1:27017
#  db: sip3
#  bulk-size: 1
#  update-period: 300000

#! Server
server:
  uri: udp://0.0.0.0:15060
  buffer-size: 65535
#  ssl:
#    key-store: ...
#    key-store-password: ...

#! Management socket
#management:
#  uri: udp://0.0.0.0:15091
#  expiration-timeout: 120000
#  expiration-delay: 60000

#! Application
#time-suffix: yyyyMMdd
#attributes:
#  record-ip-addresses: false
#  record-call-users: false
#sip:
#  message:
#    exclusions: [MESSAGE, SUBSCRIBE, NOTIFY, OPTIONS]
#    x-correlation-header: X-Call-ID
#  call:
#    expiration-delay: 1000
#    aggregation-timeout: 60000
#    termination-timeout: 5000
#    duration-timeout: 3600000
#    transaction-exclusions: [exclude-me]
#rtp-r:
#  cumulative-metrics: true
#udf:
#  check-period: 300000
#  execution-timeout: 100

#! Metrics
#metrics:
#  logging:
#    step: 1000
#  influxdb:
#    uri: http://127.0.0.1:8086
#    db: sip3
#    step: 1000
#    retention-duration: 7d
#  stasd:
#    host: 127.0.0.1
#    port: 8125
#    step: 1000
#    flavour: datadog
#  elastic:
#    host: 127.0.0.1:9200
#    index: sip3
#    step: 1000